"""empty message

Revision ID: 5e2662229614
Revises: 
Create Date: 2019-11-23 21:58:59.720065

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5e2662229614'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('wallet',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.Column('address', sa.String(), nullable=True),
    sa.Column('_encrypted_private_key', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_wallet_address'), 'wallet', ['address'], unique=True)
    op.create_index(op.f('ix_wallet_name'), 'wallet', ['name'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_wallet_name'), table_name='wallet')
    op.drop_index(op.f('ix_wallet_address'), table_name='wallet')
    op.drop_table('wallet')
    # ### end Alembic commands ###
